"""Bias-Abbildungen speichern

Revision ID: 78731178f323
Revises: df91617a6059
Erstellt: 2026-09-11 11:32:55.085538
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '78731178f323'
down_revision: str | None = 'df91617a6059'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bias_mapping',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('median_shift', sa.Float(), nullable=False),
    sa.Column('fitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['wetter.station.id'], name=op.f('fk_bias_mapping_station_id_station')),
    sa.PrimaryKeyConstraint('station_id', 'column_name', name=op.f('pk_bias_mapping')),
    schema='wetter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bias_mapping', schema='wetter')
    # ### end Alembic commands ###
