"""Grundschema: Messungen, Sensorzustaende, DWD, Modelle, Vorhersagen

Revision ID: df91617a6059
Revises: 
Erstellt: 2026-09-10 20:07:38.890644
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'df91617a6059'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dwd_hourly',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('pressure_sea_hpa', sa.Float(), nullable=True),
    sa.Column('pressure_station_hpa', sa.Float(), nullable=True),
    sa.Column('dewpoint_c', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('precip_indicator', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_dir_deg', sa.Float(), nullable=True),
    sa.Column('wind_gust_ms', sa.Float(), nullable=True),
    sa.Column('cloud_cover_okta', sa.Float(), nullable=True),
    sa.Column('sunshine_min', sa.Float(), nullable=True),
    sa.Column('visibility_m', sa.Float(), nullable=True),
    sa.Column('global_radiation_jcm2', sa.Float(), nullable=True),
    sa.Column('diffuse_radiation_jcm2', sa.Float(), nullable=True),
    sa.Column('atmo_radiation_jcm2', sa.Float(), nullable=True),
    sa.Column('vapour_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('wetbulb_c', sa.Float(), nullable=True),
    sa.Column('abs_humidity_gm3', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', name=op.f('pk_dwd_hourly')),
    schema='wetter'
    )
    op.create_index('ix_dwd_hourly_time_brin', 'dwd_hourly', ['time'], unique=False, schema='wetter', postgresql_using='brin')
    op.create_table('dwd_station',
    sa.Column('dataset_key', sa.String(length=4), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('dataset_key', name=op.f('pk_dwd_station')),
    schema='wetter'
    )
    op.create_table('model',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('lead_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model')),
    schema='wetter'
    )
    op.create_index('ix_model_lookup', 'model', ['target', 'lead_hours', 'status'], unique=False, schema='wetter')
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station')),
    sa.UniqueConstraint('key', name=op.f('uq_station_key')),
    schema='wetter'
    )
    op.create_table('forecast',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quantiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['wetter.model.id'], name=op.f('fk_forecast_model_id_model')),
    sa.ForeignKeyConstraint(['station_id'], ['wetter.station.id'], name=op.f('fk_forecast_station_id_station')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast')),
    sa.UniqueConstraint('model_id', 'issued_at', 'valid_at', 'target', name=op.f('uq_forecast_model_id')),
    schema='wetter'
    )
    op.create_index('ix_forecast_valid', 'forecast', ['valid_at', 'target'], unique=False, schema='wetter')
    op.create_table('hourly',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('pressure_station_hpa', sa.Float(), nullable=True),
    sa.Column('pressure_sea_hpa', sa.Float(), nullable=True),
    sa.Column('dewpoint_c', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_gust_ms', sa.Float(), nullable=True),
    sa.Column('wind_dir_deg', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('cloud_cover_okta', sa.Float(), nullable=True),
    sa.Column('sky_temp_c', sa.Float(), nullable=True),
    sa.Column('global_radiation_wm2', sa.Float(), nullable=True),
    sa.Column('illuminance_lux', sa.Float(), nullable=True),
    sa.Column('lightning_count', sa.Integer(), nullable=True),
    sa.Column('lightning_distance_km', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['wetter.station.id'], name=op.f('fk_hourly_station_id_station')),
    sa.PrimaryKeyConstraint('station_id', 'time', name=op.f('pk_hourly')),
    schema='wetter'
    )
    op.create_index('ix_hourly_time_brin', 'hourly', ['time'], unique=False, schema='wetter', postgresql_using='brin')
    op.create_table('measurement',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('pressure_station_hpa', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_gust_ms', sa.Float(), nullable=True),
    sa.Column('wind_dir_deg', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('sky_temp_c', sa.Float(), nullable=True),
    sa.Column('lightning_count', sa.SmallInteger(), nullable=True),
    sa.Column('lightning_distance_km', sa.Float(), nullable=True),
    sa.Column('illuminance_lux', sa.Float(), nullable=True),
    sa.Column('panel_voltage_v', sa.Float(), nullable=True),
    sa.Column('panel_current_ma', sa.Float(), nullable=True),
    sa.Column('global_radiation_wm2', sa.Float(), nullable=True),
    sa.Column('battery_v', sa.Float(), nullable=True),
    sa.Column('rssi_dbm', sa.SmallInteger(), nullable=True),
    sa.Column('power_mode', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['wetter.station.id'], name=op.f('fk_measurement_station_id_station')),
    sa.PrimaryKeyConstraint('station_id', 'time', name=op.f('pk_measurement')),
    schema='wetter'
    )
    op.create_index('ix_measurement_time_brin', 'measurement', ['time'], unique=False, schema='wetter', postgresql_using='brin', postgresql_with={'pages_per_range': 64})
    op.create_table('sensor_state',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('sensor_key', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['wetter.station.id'], name=op.f('fk_sensor_state_station_id_station')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_state')),
    schema='wetter'
    )
    op.create_index('ix_sensor_state_lookup', 'sensor_state', ['station_id', 'sensor_key', 'valid_from'], unique=False, schema='wetter')
    op.create_table('verification',
    sa.Column('forecast_id', sa.BigInteger(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed', sa.Float(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['wetter.forecast.id'], name=op.f('fk_verification_forecast_id_forecast')),
    sa.PrimaryKeyConstraint('forecast_id', name=op.f('pk_verification')),
    schema='wetter'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification', schema='wetter')
    op.drop_index('ix_sensor_state_lookup', table_name='sensor_state', schema='wetter')
    op.drop_table('sensor_state', schema='wetter')
    op.drop_index('ix_measurement_time_brin', table_name='measurement', schema='wetter', postgresql_using='brin', postgresql_with={'pages_per_range': 64})
    op.drop_table('measurement', schema='wetter')
    op.drop_index('ix_hourly_time_brin', table_name='hourly', schema='wetter', postgresql_using='brin')
    op.drop_table('hourly', schema='wetter')
    op.drop_index('ix_forecast_valid', table_name='forecast', schema='wetter')
    op.drop_table('forecast', schema='wetter')
    op.drop_table('station', schema='wetter')
    op.drop_index('ix_model_lookup', table_name='model', schema='wetter')
    op.drop_table('model', schema='wetter')
    op.drop_table('dwd_station', schema='wetter')
    op.drop_index('ix_dwd_hourly_time_brin', table_name='dwd_hourly', schema='wetter', postgresql_using='brin')
    op.drop_table('dwd_hourly', schema='wetter')
    # ### end Alembic commands ###
